### ISSUE TITLE
Syntax error in Python3

### ISSUE THREAD

**Issue by wzyboy** [jimmyxu/chnroutes#4]
When running the script when <code>env python</code> returns to Python 3.2.3, a syntax error will occured:

<pre>  File "chnroutes-jimmy.py", line 45
    os.chmod('vpn-up.sh', 00755)
                              ^
SyntaxError: invalid token</pre>

Either change <code>env python</code> to <code>env python2</code> or run the script with <code>python2 chnroutes.py</code> will be a workaround.

Suggesting change the code to meet the syntax of Python 3.

**Comment by jimmyxu** [comment]
没打算支持python3，而且不是所有发行版都有python2这个链接。
